# Generated by Django 5.1.6 on 2025-03-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('energy_demand', models.FloatField()),
                ('energy_supply', models.FloatField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_energy_generated', models.FloatField()),
                ('fossil_fuel_offset', models.FloatField()),
                ('co2_reduction', models.FloatField()),
            ],
        ),
    ]
