# Generated by Django 5.1.6 on 2025-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('solar_output', models.FloatField()),
                ('wind_output', models.FloatField()),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ForecastData',
        ),
    ]
