# Generated by Django 5.1.6 on 2025-02-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment_id', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('pressure', models.FloatField()),
                ('failure_risk', models.FloatField(default=0.0)),
            ],
        ),
    ]
